spring:
 application:
   name: microservice-order

   microservice-customer:
     url: http://localhost:8080/customer/api/v1/
     #url: https://customer.microservicesdemo.net/customer/api/v1/

 #data:
   #mongodb:
     #uri: mongodb+srv://mkmongouser:Secret_Password@cluster0.yu4x6.mongodb.net
     #uri: mongodb://AdminUser:123456qwerty@localhost:27017/CustomerOrderDB?authSource=admin&authMechanism=SCRAM-SHA-256
     #database: CustomerOrderDB
     #authentication-database: admin
     #username: AdminUser
     #password: 123456qwerty
     #authentication-mechanism: SCRAM-SHA-256

server:
 port: 8090
 servlet:
   context-path: /order

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics

    health:
      show-details: always

  metrics:
    tags:
      application: MonitoringOrderMicroservice